# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_ledger_payout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idempotency",
            name="key",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="idempotency",
            name="response_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idempotency",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "In progress"), ("completed", "Completed")],
                default="completed",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="idempotency",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "In progress"), ("completed", "Completed")],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="idempotency",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="idempotency",
            constraint=models.UniqueConstraint(
                fields=("merchant", "key"), name="unique_idempotency_key_per_merchant"
            ),
        ),
    ]
