# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_harden_idempotency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
