# Generated by Django 5.2.13 on 2026-04-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_payout_retry_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="idempotency",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="type",
            field=models.CharField(
                choices=[("credit", "Credit"), ("debit", "Debit")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="payout",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
